References: https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [23]:
# Import NumPy
import numpy as np

#### Q. Stack arrays a and b vertically

Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

Desired Output:

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

In [24]:
# method 1
a = np.arange(10)
print(a)

a = a.reshape(2,-1)
print(a)

b = np.repeat(1,10)
print(b)

b = b.reshape(2, -1)
print(b)

c = np.vstack((a, b))
print(c)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[1 1 1 1 1 1 1 1 1 1]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [25]:
c = np.stack((a,b))
print(c)

[[[0 1 2 3 4]
  [5 6 7 8 9]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]


In [28]:
# method 2
np.concatenate([a, b])   # Join a sequence of arrays along an existing axis.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
# method 3 r_ Translates slice objects to concatenation along the first axis.
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### Q. Stack the arrays a and b horizontally.

Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

Desired Output:

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [31]:
np.concatenate([a, b], axis = 1) 

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [32]:
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [33]:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

#### Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])`

Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [41]:
a = np.array([1,2,3])
b = np.repeat(a, 3) # repeat each component
c = np.tile(a, 3)  # Construct an array by repeating A the number of times given by reps
print(b)
print(c)
np.r_[b, c]

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

#### Q. Get the common items between a and b

In [42]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

#### Q. From array a remove all items present in array b

Input:

a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

Desired Output:

array([1,2,3,4])

In [43]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a, b)

array([1, 2, 3, 4])

#### Q. Get the positions where elements of a and b match

In [44]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

#### Q. Get all items between 5 and 10 from a.

In [56]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a[(a >= 5) & (a <= 10)])

index = np.where((a >= 5) & (a <= 10))
a[index]

[ 6  9 10]


array([ 6,  9, 10])

More exercises:
- https://github.com/rougier/numpy-100 
- https://www.machinelearningplus.com/python/101-numpy-exercises-python/
- https://www.kaggle.com/utsav15/100-numpy-exercises