## NumPy Broadcasting

https://www.datacamp.com/community/tutorials/python-numpy-tutorial#broadcasting

https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

it’s a mechanism that allows NumPy to work with arrays of different shapes when you’re performing arithmetic operations.

Broadcasting can be done if:
- the dimensions of your arrays need to be compatible. 
 - when they are equal.
 - when one of them is 1 
 - if they are compatible in all dimensions.
 
If these conditions are not met, a ValueError: operands could not be broadcast together exception is thrown

In [2]:
import numpy as np

In [11]:
# when they are equal
x = np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
print(x.shape)

(3, 4)


In [7]:
y = np.random.random((3,4))
print(y)

[[0.62365645 0.33143832 0.93929634 0.94470308]
 [0.42232599 0.31687958 0.70237835 0.62741952]
 [0.32583359 0.98577658 0.43801011 0.09667383]]


In [8]:
print(x.shape == y.shape)

True


In [10]:
x + y

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [13]:
# when one of them is 1 

# Initialize `x`
x = np.ones((3,4))

# Check shape of `x`
print(x.shape)

# Initialize `y`
y = np.arange(4)

# Check shape of `y`
print(y.shape)

# Subtract `x` and `y`
z = x - y 
print(z)
print(z.shape)

(3, 4)
(4,)
[[ 1.  0. -1. -2.]
 [ 1.  0. -1. -2.]
 [ 1.  0. -1. -2.]]
(3, 4)


In [15]:
# if they are compatible in all dimensions.
# Initialize `x` and `y`
x = np.ones((3,4))
print(x.shape)
y = np.random.random((5,1,4))
print(y.shape)
# Add `x` and `y`
z = x + y
print(z.shape)

(3, 4)
(5, 1, 4)
(5, 3, 4)
