# Day 2: Numpy Array
## <a href="https://www.datacamp.com/community/tutorials/python-numpy-tutorial">Python Numpy Tutorial Datacamp</a>

We are interested in Numpy Array. More benefit compare to normal python list as follow:
<ul>
<li>being more compact</li>
<li>faster access in reading and writing items</li>
<li>being more convenient and more efficient</li>
</ul>

Numpy Cheat sheet: https://www.datacamp.com/community/blog/python-numpy-cheat-sheet

### What is Numpy Array?
- Numpy = Numeric Python = scientific computing library contains collection of tools and tecnique.

- Numpy Array = High-performance multidimensional array object

- An array contains: 
<ul>
<li>information about the raw data</li>
<li>how to locate an elements</li>
<li>how to interpret an element</li>
</ul>

- Numpy Array attributes: 
<ul>
<li>data: memory address that array located</li>
<li>shape: shape of array</li>
<li>dtype: type of array</li>
<li>strides: number of byte should be skipped memory to go to next element</li>
</ul>

- 1D
- 2D:
     row = axis0,
     column = axis1
- 3D
    

In [2]:
#Import Numpy as np
import numpy as np

In [3]:
#create array when know what the data is
my_array = np.array([[1,2,3,4], [5,6,7,8]], dtype = np.int64)

In [4]:
#print array
print(my_array)

[[1 2 3 4]
 [5 6 7 8]]


### Create Array : initial placeholder

In [6]:
#create array from another sources
#initial placeholders = empty array then fill up afterward

# Create an array of ones
np.ones((3,4))

# Create an array of zeros
np.zeros((2,3,4),dtype=np.int16)

# Create an array with random values
np.random.random((2,2))

# Create an empty array
np.empty((3,2))

# Create a full array
np.full((2,2),7)

# Create an array of evenly-spaced values
np.arange(10,25,5)

# Create an array of evenly-spaced values
np.linspace(0,2,9)

#An identity matrix is a square matrix of which all elements in 
#the principal diagonal are ones, all other elements are zeros. 
np.eye(4)

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Load NumPy array from Text

- loadtxt() works when each row in the text file has the same number of values
- genfromtxt() more flexible and hablde missing value easier; detail in https://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html#numpy.genfromtxt


### Save NumPy Arrays

In [10]:
x = np.arange(0.0,5.0,1.0)
np.savetxt('test_save_numpy_array.out', x, delimiter=',')

### Numpy Attributes

In [12]:
print(my_array)

# Print the number of `my_array`'s dimensions
print(my_array.ndim)

# Print the number of `my_array`'s elements
print(my_array.size)

# Print information about `my_array`'s memory layout
print(my_array.flags)

# Print the length of one array element in bytes
print(my_array.itemsize)

# Print the total consumed bytes by `my_array`'s elements
print(my_array.nbytes)

[[1 2 3 4]
 [5 6 7 8]]
2
8
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

8
64
