References: https://www.machinelearningplus.com/python/101-numpy-exercises-python/

#### Q. Import numpy as np and print the version number.

In [2]:
import numpy as np
print(np.__version__)

1.17.2


#### Q. Create a 1D array of numbers from 0 to 9

Desired output:

#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
# solution 1
my_array = np.array([0,1,2,3,4,5,6,7,8,9])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# solution 2
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Q. Create a 3×3 numpy array of all True’s

In [41]:
my_array = np.full((3,3), True, dtype=bool)
my_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

- numpy.full(shape, fill_value, dtype=None, order='C')
Return a new array of given shape and type, filled with fill_value.

    Parameters:	
        shape : int or sequence of ints 
        Shape of the new array, e.g., (2, 3) or 2.

        fill_value : scalar Fill value.

        dtype : data-type, optional 
        The desired data-type for the array The default, None, means : np.array(fill_value).dtype.

        order : {‘C’, ‘F’}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous (row- or column-wise) order in memory.

- Returns:	
out : ndarray
Array of fill_value with the given shape, dtype, and order.

#### Q. How to extract items that satisfy a given condition from 1D array?

Extract all odd numbers from arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired output:

#> array([1, 3, 5, 7, 9])

In [40]:
# solution 1
arr = np.array([0,1,2,3,4,5,6,7,8,9])
condition = np.mod(arr, 2)!=0
print(condition)
extract_arr = np.extract(condition, arr)
extract_arr

[False  True False  True False  True False  True False  True]


array([1, 3, 5, 7, 9])

In [28]:
# solution 2
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

#### Q. Replace all odd numbers in arr with -1

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [34]:
# solution 1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [36]:
# solution 2
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)
condition = np.mod(arr, 2) != 0
np.place(arr, condition, [-1])
arr

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### Q. Replace all odd numbers in arr with -1 without changing arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

out

#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr = np.arange(10)
arr
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### Q. Convert a 1D array to a 2D array with 2 rows

Input:

np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

#> array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

In [57]:
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])